# server
server:
  port: 80
# spring
spring:
  # application
  application:
    name: zuul
  # session
  session:
    store-type: redis
    redis:
      flush-mode: immediate
  # redis
  redis:
    host: localhost
    database: 0
    port: 6379
    # jedis pool
    jedis:
      pool:
        max-active: 8
# eureka
eureka:
  # eureka client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# zuul
zuul:
  # 不设置敏感的header, 默认值为"Cookie", "Set-Cookie", "Authorization"
  sensitive-headers:
  add-host-header: true
#  routes:
#    home:
#      path: /
#      serviceId: expenditure-supervise-local
#    expenditure-supervise:
#      path: /expenditure-supervise-local/**
#      serviceId: expenditure-supervise-local
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.lshaci: info
