# server
server:
  port: 8081
# spring
spring:
  # application
  application:
    name: gateway
  # redis
  redis:
    host: localhost
    database: 0
    port: 6379
    # jedis pool
    jedis:
      pool:
        max-active: 8
  # spring cloud
  cloud:
    # spring cloud gateway
    gateway:
      routes:
      - id: after_route
        uri: http://www.baidu.com
        predicates:
        - After=2019-08-08T15:40:00+08:00[Asia/Shanghai]
      - id: before_route
        uri: http://www.qq.com
        predicates:
        - Before=2019-08-08T14:40:00+08:00[Asia/Shanghai]
      - id: between_route
        uri: http://www.bilibili.com
        predicates:
        - Between=2019-08-08T14:50:00+08:00[Asia/Shanghai], 2019-08-08T15:40:00+08:00[Asia/Shanghai]
      - id: email_host
        uri: http://www.163.com
        predicates:
        - Path=/email
      discovery:
        locator:
          # 开启通过eureka中的service id进行路由
          enabled: true
          # 开启支持service id小写（spring.application.name中不能有下划线）
          lower-case-service-id: true
          # 定义过滤器
#          filters:
#          # 去掉url中的第二个前缀
#          # http://localhost/user/api/college/getAll   -->   http://localhost/user/college/getAll
#          - StripPrefix=2
# eureka
eureka:
  # eureka client
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.lshaci: info
